# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-03 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentBreakdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payable_name', models.CharField(max_length=50)),
                ('fee_amount', models.FloatField()),
                ('year_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollment.YearLevel')),
            ],
            options={
                'verbose_name': 'EnrollmentBreakdown',
                'verbose_name_plural': 'EnrollmentBreakdowns',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentORDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_given', models.FloatField()),
                ('particular_name', models.CharField(choices=[('ENROLLMENT', 'Enrollment Fee'), ('TUITION', 'Tuition Fee')], max_length=50)),
                ('month', models.CharField(blank=True, choices=[('JAN', 'January'), ('FEB', 'Febuary'), ('MAR', 'March'), ('APR', 'April'), ('MAY', 'May'), ('JUN', 'June'), ('JUL', 'July'), ('AUG', 'August'), ('SEP', 'September'), ('OCT', 'October'), ('NOV', 'November'), ('DEC', 'December')], max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'OR_Details',
                'verbose_name_plural': 'OR_Detailss',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentTransactionsMade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paid', models.DateField(auto_now=True)),
                ('ORnum', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Promissory', 'Others'), ('Others', 'Others')], max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Enrollment')),
            ],
            options={
                'verbose_name': 'EnrollmentTransactionsMade',
                'verbose_name_plural': 'EnrollmentTransactionsMades',
            },
        ),
        migrations.CreateModel(
            name='OthersORDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_item', models.CharField(max_length=50)),
                ('item_price', models.FloatField()),
                ('money_given', models.FloatField()),
            ],
            options={
                'verbose_name': 'OthersORDetails',
                'verbose_name_plural': 'OthersORDetailss',
            },
        ),
        migrations.CreateModel(
            name='OthersTransactionsMade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paid', models.DateField()),
                ('ORnum', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Enrollment')),
            ],
            options={
                'verbose_name': 'OthersTransactionsMade',
                'verbose_name_plural': 'OthersTransactionsMades',
            },
        ),
        migrations.AddField(
            model_name='othersordetails',
            name='ORnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.OthersTransactionsMade'),
        ),
        migrations.AddField(
            model_name='enrollmentordetails',
            name='ORnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.EnrollmentTransactionsMade'),
        ),
    ]
